services:
  app:
    build: .
    container_name: mini-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      APP_VERSION: "1.0.0"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
